apiVersion: v1
name: apim3
# When the version is modified, make sure the artifacthub.io/changes list is updated
# Also update CHANGELOG.md
version: 3.2.0
appVersion: 3.20.1
description: Official Gravitee.io Helm chart for API Management 3.x
home: https://gravitee.io
sources:
  - https://github.com/gravitee-io
icon: https://avatars2.githubusercontent.com/u/12655666?s=200&v=4
keywords:
  - gravitee.io
  - gravitee
  - graviteeio 
  - API
  - API Management
kubeVersion: ">=1.14.0-0"
annotations:
  # List of changes for the release in artifacthub.io
  # https://artifacthub.io/packages/helm/graviteeio/apim3?modal=changelog
  artifacthub.io/changes: |
    - Allow disabling analytics in Management API
    - BREAKING CHANGE Move Probes configuration under `deployment:`
    - BREAKING CHANGE Change probe default configuration
    - BREAKING CHANGE Remove `apiSync` parameter under `gateway.readinessProbe`
    - Allow users to define their own `customStartupProbe` `customReadinessProbe` `customlivenessProbe`
    - Update default version of MongoDB in values. Set it to 6.0.6
