apiVersion: v1
name: apim3
# When the version is modified, make sure the artifacthub.io/changes list is updated
# Also update CHANGELOG.md
version: 3.1.3
appVersion: 3.6.0
description: Official Gravitee.io Helm chart for API Management 3.x
home: https://gravitee.io
sources:
  - https://github.com/gravitee-io
icon: https://avatars2.githubusercontent.com/u/12655666?s=200&v=4
keywords:
  - gravitee.io
  - gravitee
  - graviteeio 
  - API
  - API Menagement
kubeVersion: ">=1.16.0-0"
