apiVersion: v1
name: apim3
# When the version is modified, make sure the artifacthub.io/changes list is updated
# Also update CHANGELOG.md
version: 3.1.62
appVersion: 3.20.1
description: Official Gravitee.io Helm chart for API Management 3.x
home: https://gravitee.io
sources:
  - https://github.com/gravitee-io
icon: https://avatars2.githubusercontent.com/u/12655666?s=200&v=4
keywords:
  - gravitee.io
  - gravitee
  - graviteeio 
  - API
  - API Management
kubeVersion: ">=1.14.0-0"
annotations:
  # List of changes for the release in artifacthub.io
  # https://artifacthub.io/packages/helm/graviteeio/apim3?modal=changelog
  artifacthub.io/changes: |
    - Remove `/gateway` from the gateway ingress path
    - Add `labels` in metrics config of the Management API and Gateway
    - Fix default ingress path for ui
    - Add API properties config of the Management API and Gateway
    - Update APIM version to 3.20.1
    - Update Elasticsearch version to 7.17.9
    - Update MongoDB version to 5.0.14