dependencies:
  - name: elasticsearch
    version: ^17.9.29
    repository: https://charts.bitnami.com/bitnami
    condition: elasticsearch.enabled
  - name: mongodb
    version: ^12.1.7
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
