dependencies:
  - name: elasticsearch
    version: ^19.0.0
    repository: https://charts.bitnami.com/bitnami
    condition: elasticsearch.enabled
  - name: mongodb
    alias: mongodb-replicaset
    version: ^12.1.7
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb-replicaset.enabled
