dependencies:
- name: elasticsearch
  version: ^1.27.3
  repository: https://charts.helm.sh/stable
  condition: elasticsearch.enabled
- name: mongodb-replicaset
  version: ^3.10.1
  repository: https://charts.helm.sh/stable
  condition: mongodb-replicaset.enabled
