dependencies:
  - name: elasticsearch
    version: ^1.27.3
    repository: https://charts.helm.sh/stable
    condition: elasticsearch.enabled
  - name: mongodb
    version: ^11.2.0
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
