{{- if .Values.api.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "gravitee.api.fullname" . }}
  labels:
    app: {{ template "gravitee.name" . }}
    component: "{{ .Values.api.name }}"
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: "{{ .Values.api.service.type }}"
  ports:
    - port: {{ .Values.api.service.externalPort }}
      targetPort: {{ .Values.api.service.internalPort }}
      protocol: TCP
      name: {{ .Values.api.name }}
    {{- if .Values.api.http.services.core.service.enabled }}
    - port: {{ .Values.api.http.services.core.service.externalPort }}
      targetPort: {{ .Values.api.http.services.core.http.port }}
      protocol: TCP
      name: {{ .Values.api.name }}-technical
    {{- end }}
  selector:
    app: {{ template "gravitee.name" . }}
    component: "{{ .Values.api.name }}"
    release: {{ .Release.Name }}
{{- end -}}