{{- if .Values.api.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "gravitee.api.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "gravitee.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: "{{ .Values.api.name }}"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  type: "{{ .Values.api.service.type }}"
  ports:
    - port: {{ .Values.api.service.externalPort }}
      targetPort: {{ .Values.api.service.internalPort }}
      protocol: TCP
      name: {{ .Values.api.name }}
    {{- if .Values.api.http.services.core.service.enabled }}
    - port: {{ .Values.api.http.services.core.service.externalPort }}
      targetPort: {{ .Values.api.http.services.core.http.port }}
      protocol: TCP
      name: {{ .Values.api.name }}-technical
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ template "gravitee.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "{{ .Values.api.name }}"
{{- end -}}