apiVersion: v1
name: am
# When the version is modified, make sure the artifacthub.io/changes list is updated
# Also update CHANGELOG.md
version: 1.0.57
appVersion: 3.20.1
description: Official Gravitee.io Helm chart for Access Management
home: https://gravitee.io
sources:
  - https://github.com/gravitee-io
icon: https://avatars2.githubusercontent.com/u/12655666?s=200&v=4
keywords:
  - gravitee.io
  - gravitee
  - graviteeio
  - oauth2
  - oidc
  - authentication
  - API
  - security
kubeVersion: ">=1.14.0-0"
annotations:
  # List of changes for the release in artifacthub.io
  # https://artifacthub.io/packages/helm/graviteeio/am?modal=changelog
  artifacthub.io/changes: |
    - Add hook-delete-policy
    - Remove ingress nginx annotation when `ingress.class` is not nginx
    - Allow users to use `logging.debug: true` when they define their own configuration file by defining a volume
