apiVersion: v1
name: am
# When the version is modified, make sure the artifacthub.io/changes list is updated
# Also update CHANGELOG.md
version: 1.0.13
appVersion: 3.5.0
description: Official Gravitee.io Helm chart for Access Management
home: https://gravitee.io
sources:
  - https://github.com/gravitee-io
icon: https://avatars2.githubusercontent.com/u/12655666?s=200&v=4
keywords:
  - gravitee.io
  - gravitee
  - graviteeio 
  - oauth2
  - oidc
  - authentication
  - API
  - security
kubeVersion: ">=1.16.0-0"