{{- if .Values.portal.enabled -}}
{{- if .Values.portal.podDisruptionBudget.enabled -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "gravitee.portal.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "gravitee.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: "{{ .Values.portal.name }}"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  {{- if .Values.portal.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.portal.podDisruptionBudget.maxUnavailable }}
  {{ end -}}
  {{- if .Values.portal.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.portal.podDisruptionBudget.minAvailable }}
  {{ end -}}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "gravitee.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: "{{ .Values.portal.name }}"
{{- end -}}
{{- end -}}