{{- if .Values.portal.enabled -}}
{{- if .Values.portal.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "gravitee.portal.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "gravitee.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: "{{ .Values.portal.name }}"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "gravitee.portal.fullname" . }}
  minReplicas: {{ .Values.portal.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.portal.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{ .Values.portal.autoscaling.targetAverageUtilization }}
{{- if .Values.portal.autoscaling.targetMemoryAverageUtilization }}
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: {{ .Values.portal.autoscaling.targetMemoryAverageUtilization }}
{{- end -}}
{{- end -}}
{{- end -}}
