{{- if .Values.engine.services.core.http.enabled -}}
{{- if .Values.engine.services.core.ingress.enabled -}}
{{- $serviceAPIName := include "gravitee.engine.fullname" . -}}
{{- $serviceAPIPort := .Values.engine.services.core.service.externalPort -}}
{{- $ingressPath   := .Values.engine.services.core.ingress.path -}}
{{- $apiVersion := include "common.capabilities.ingress.apiVersion" . -}}
apiVersion: {{ $apiVersion }}
kind: Ingress
metadata:
  name: {{ template "gravitee.engine.fullname" . }}-technical
  labels:
    app.kubernetes.io/name: {{ template "gravitee.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Values.engine.image.tag | default .Chart.AppVersion | quote }}
    app.kubernetes.io/component: "{{ .Values.engine.name }}"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  annotations:
    {{- if .Values.engine.services.core.ingress.annotations }}
    {{- include "common.ingress.annotations.render" (dict "annotations" .Values.engine.services.core.ingress.annotations "ingressClassName" .Values.engine.services.core.ingress.ingressClassName "context" $) | nindent 4 }}
    {{- end }}
spec:
  {{- if and .Values.engine.services.core.ingress.ingressClassName (include "common.ingress.supportsIngressClassname" .) }}
  ingressClassName: {{ .Values.engine.services.core.ingress.ingressClassName | quote }}
  {{- end }}
  rules:
  {{- range $host := .Values.engine.services.core.ingress.hosts }}
  - host: {{ $host }}
    http:
      paths:
      - pathType: Prefix
        path: {{ $ingressPath }}
        backend:
          {{- if (eq $apiVersion "networking.k8s.io/v1") }}
          service:
            name: {{ $serviceAPIName }}
            port:
              number: {{ $serviceAPIPort }}
          {{ else }}
          serviceName: {{ $serviceAPIName }}
          servicePort: {{ $serviceAPIPort }}
          {{- end -}}
  {{- end -}}
  {{- if .Values.engine.services.core.ingress.tls }}
  tls:
{{ toYaml .Values.engine.services.core.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
{{- end -}}
