{{- if and (.Values.engine.enabled) (.Values.engine.autoscaling.enabled) -}}
{{- $apiVersion := include "common.capabilities.autoscaling.apiVersion" . -}}
apiVersion: {{ $apiVersion }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "gravitee.engine.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "gravitee.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Values.engine.image.tag | default .Chart.AppVersion | quote }}
    app.kubernetes.io/component: "{{ .Values.engine.name }}"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: {{ .Values.engine.type }}
    name: {{ template "gravitee.engine.fullname" . }}
  minReplicas: {{ .Values.engine.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.engine.autoscaling.maxReplicas }}
  metrics:
{{- if .Values.engine.autoscaling.targetMemoryAverageUtilization }}
  - type: Resource
    resource:
      name: memory
      {{- if (eq $apiVersion "autoscaling/v2") }}
      target:
        type: Utilization
        averageUtilization: {{ .Values.engine.autoscaling.targetMemoryAverageUtilization }}
      {{ else }}
      targetAverageUtilization: {{ .Values.engine.autoscaling.targetMemoryAverageUtilization }}
      {{- end -}}
{{- end }}
  - type: Resource
    resource:
      name: cpu
      {{- if (eq $apiVersion "autoscaling/v2") }}
      target:
        type: Utilization
        averageUtilization: {{ .Values.engine.autoscaling.targetAverageUtilization }}
      {{ else }}
      targetAverageUtilization: {{ .Values.engine.autoscaling.targetAverageUtilization }}
      {{- end -}}
{{- end }}
