{{- if .Values.engine.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "gravitee.engine.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "gravitee.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Values.engine.image.tag | default .Chart.AppVersion | quote }}
    app.kubernetes.io/component: "{{ .Values.engine.name }}"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  annotations:
    {{- range $key, $value := .Values.engine.service.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  type: "{{ .Values.engine.service.type }}"
  ports:
    - port: {{ .Values.engine.service.externalPort }}
      targetPort: {{ .Values.engine.service.internalPort }}
      protocol: TCP
      name: {{ .Values.engine.name }}
    - port: 5701
      name: {{ .Values.engine.name }}-hz
      protocol: TCP
    {{- if .Values.engine.services.core.service.enabled }}
    - port: {{ .Values.engine.services.core.service.externalPort }}
      targetPort: {{ .Values.engine.services.core.http.port }}
      protocol: TCP
      name: {{ .Values.engine.name }}-techapi
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ template "gravitee.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "{{ .Values.engine.name }}"
{{- end -}}
