{{- if not (lookup "v1" "Secret" .Release.Namespace .Values.license.name) }}
{{- with .Values.license }}
{{- if .key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
type: Opaque
data:
  licensekey: {{ .key }}
{{- end -}}
{{- end -}}
{{- end -}}
