dependencies:
- name: elasticsearch
  version: ^1.22.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: es.enabled
- name: mongodb-replicaset
  version: ^3.9.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: mongodb.enabled