{{- if .Values.api.enabled -}}
{{- if .Values.api.ingress.management.enabled -}}
{{- $serviceAPIName := include "gravitee.api.fullname" . -}}
{{- $serviceAPIPort := .Values.api.service.externalPort -}}
{{- $ingressPath   := .Values.api.ingress.management.path -}}
apiVersion: {{ template "ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ template "gravitee.api.fullname" . }}-management
  labels:
    app.kubernetes.io/name: {{ template "gravitee.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: "{{ .Values.api.name }}"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  annotations:
    {{- range $key, $value := .Values.api.ingress.management.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    {{- range $host := .Values.api.ingress.management.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $serviceAPIName }}
              servicePort: {{ $serviceAPIPort }}
    {{- end -}}
  {{- if .Values.api.ingress.management.tls }}
  tls:
{{ toYaml .Values.api.ingress.management.tls | indent 4 }}
  {{- end -}}
{{- end -}}
{{- end -}}