{{- if .Values.cookpit.managedServiceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "cookpit.serviceAccount" . }}
  annotations:
    {{- with .Values.cookpit.serviceAccountAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    app.kubernetes.io/name: {{ template "gravitee.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: "{{ .Values.cookpit.name }}"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end -}}