{{- if .Values.am.managedServiceAccount }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "am.serviceAccount" . }}-role
  labels:
    app.kubernetes.io/name: {{ template "gravitee.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Values.api.image.tag | default .Chart.AppVersion | quote }}
    app.kubernetes.io/component: "{{ .Values.am.name }}"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules: {{ toYaml .Values.am.roleRules | nindent 2 -}}
{{- end -}}
