dependencies:
- name: elasticsearch
  version: ^1.27.3
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: elasticsearch.enabled
- name: mongodb-replicaset
  version: ^3.10.1
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: mongodb-replicaset.enabled
- name: redis
  version: ^10.6.9
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
