{{- if .Values.ui.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "gravitee.ui.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "gravitee.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: "{{ .Values.ui.name }}"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
data:
  use-gzip: "true"
  gzip-level: "5"
  gzip-types: "*"
  constants.json: |
    {
      {{- if .Values.ui.api_url }}
      "API_URL": "{{ .Values.ui.api_url }}",
      {{- else }}
      "API_URL": "https://{{ index .Values.api.ingress.hosts 0 }}{{ .Values.api.ingress.path }}",
      {{- end }}
      "GRAVITEE_ENABLED": true,
      "GRAVITEE_MANAGEMENT_UI_URL": "{{ .Values.apim.console.url }}"
    }
{{- end -}}