{{- if .Values.ui.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "gravitee.ui.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "gravitee.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: "{{ .Values.ui.name }}"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  annotations:
    {{- range $key, $value := .Values.ui.service.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  type: "{{ .Values.ui.service.type }}"
  ports:
    - port: {{ .Values.ui.service.externalPort }}
      targetPort: {{ .Values.ui.service.internalPort }}
      protocol: TCP
      name: {{ .Values.ui.name | trunc 63 | trimSuffix "-" }}
  selector:
    app.kubernetes.io/name: {{ template "gravitee.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "{{ .Values.ui.name }}"
{{- end -}}
