{{- if .Values.ui.enabled -}}
{{- if .Values.ui.ingress.enabled -}}
{{- $serviceAPIName := include "gravitee.ui.fullname" . -}}
{{- $serviceAPIPort := .Values.ui.service.externalPort -}}
{{- if .Values.ui.ingress.route.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
{{- else }}
apiVersion: extensions/v1beta1
kind: Ingress
{{- end }}
metadata:
  name: {{ template "gravitee.ui.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "gravitee.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion  }}
    app.kubernetes.io/component: "{{ .Values.api.name }}"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  annotations:
    {{- range $key, $value := .Values.ui.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  {{- if .Values.ui.ingress.route.enabled }}
  host: {{ .Values.ui.ingress.hosts | first }}
  path: /
  port:
    targetPort: ui
  tls:
    termination: edge
  to:
    kind: Service
    name: {{ template "gravitee.ui.fullname" . }}
    weight: 100
  wildcardPolicy: None
  {{- else -}}
  rules:
    {{- range $host := .Values.ui.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $serviceAPIName }}
              servicePort: {{ $serviceAPIPort }}
    {{- end -}}
  {{- if .Values.ui.ingress.tls }}
  tls:
{{ toYaml .Values.ui.ingress.tls | indent 4 }}
  {{- end -}}
  {{- end -}}
{{- end -}}
{{- end -}}
