{{- if .Values.api.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "gravitee.api.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "gravitee.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Values.api.image.tag | default .Chart.AppVersion | quote }}
    app.kubernetes.io/component: "{{ .Values.api.name }}"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  annotations:
    {{- range $key, $value := .Values.api.service.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  type: "{{ .Values.api.service.type }}"
  ports:
    - name: {{ .Values.api.name }}-http
      port: {{ .Values.api.service.externalPort }}
      targetPort: {{ .Values.api.service.internalPortName }}
      protocol: TCP
    {{- if .Values.api.controller.ws.service.enabled }}
    - name: {{ .Values.api.name }}-ws
      port: {{ .Values.api.controller.ws.service.externalPort }}
      targetPort: {{ .Values.api.controller.ws.service.internalPortName }}
      protocol: TCP
    {{- end }}
    {{- if .Values.api.http.services.core.service.enabled }}
    - name: {{ .Values.api.name }}-technical
      port: {{ .Values.api.http.services.core.service.externalPort }}
      targetPort: {{ .Values.api.http.services.core.service.internalPortName }}
      protocol: TCP
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ template "gravitee.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "{{ .Values.api.name }}"
{{- end -}}
