{{- if and (.Values.gateway.enabled) (.Values.gateway.autoscaling.enabled) -}}
{{- $apiVersion := include "common.capabilities.autoscaling.apiVersion" . -}}
apiVersion: {{ $apiVersion }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "gravitee.gateway.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "gravitee.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Values.gateway.image.tag | default .Chart.AppVersion | quote }}
    app.kubernetes.io/component: "{{ .Values.gateway.name }}"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    {{- if .Values.common.labels }}
    {{- range $key, $value := .Values.common.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
  annotations:
    {{- $annotations := dict }}
    {{- if .Values.common.annotations }}
    {{- $annotations = merge $annotations .Values.common.annotations }}
    {{- end }}
    {{- range $key, $value := $annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: {{ .Values.gateway.type }}
    name: {{ template "gravitee.gateway.fullname" . }}
  minReplicas: {{ .Values.gateway.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.gateway.autoscaling.maxReplicas }}
  metrics:
{{- if .Values.gateway.autoscaling.targetMemoryAverageUtilization }}
  - type: Resource
    resource:
      name: memory
      {{- if (ne $apiVersion "autoscaling/v2beta1") }}
      target:
        type: Utilization
        averageUtilization: {{ .Values.gateway.autoscaling.targetMemoryAverageUtilization }}
      {{ else }}
      targetAverageUtilization: {{ .Values.gateway.autoscaling.targetMemoryAverageUtilization }}
      {{- end -}}
{{- end }}
  - type: Resource
    resource:
      name: cpu
      {{- if (ne $apiVersion "autoscaling/v2beta1") }}
      target:
        type: Utilization
        averageUtilization: {{ .Values.gateway.autoscaling.targetAverageUtilization }}
      {{ else }}
      targetAverageUtilization: {{ .Values.gateway.autoscaling.targetAverageUtilization }}
      {{- end -}}
{{- end -}}
