{{- if .Values.gateway.enabled -}}
{{- if .Values.gateway.ingress.enabled -}}
{{- $serviceGWName := include "gravitee.gateway.fullname" . -}}
{{- $serviceGWPort := .Values.gateway.service.externalPort -}}
{{- $ingressPath   := .Values.gateway.ingress.path -}}
{{- $apiVersion := include "common.capabilities.ingress.apiVersion" . -}}
apiVersion: {{ $apiVersion }}
kind: Ingress
metadata:
  name: {{ template "gravitee.gateway.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "gravitee.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Values.gateway.image.tag | default .Chart.AppVersion | quote }}
    app.kubernetes.io/component: "{{ .Values.gateway.name }}"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  {{- if .Values.gateway.ingress.annotations }}
  annotations:
    {{- include "common.ingress.annotations.render" (dict "annotations" .Values.gateway.ingress.annotations "ingressClassName" .Values.gateway.ingress.ingressClassName "openshift" .Values.openshift "context" $) | nindent 4 }}
  {{- end }}
spec:
  {{- if and (eq (include "common.ingress.supportsIngressClassname" .) "true") (.Values.gateway.ingress.ingressClassName) (ne .Values.gateway.ingress.ingressClassName "none") }}
  ingressClassName: {{ .Values.gateway.ingress.ingressClassName | quote }}
  {{- end }}
  rules:
  {{- range $host := .Values.gateway.ingress.hosts }}
  - host: {{ $host }}
    http:
      paths:
      - pathType: Prefix
        path: {{ $ingressPath }}
        backend:
          {{- if (eq $apiVersion "networking.k8s.io/v1") }}
          service:
            name: {{ $serviceGWName }}
            port:
              number: {{ $serviceGWPort }}
          {{ else }}
          serviceName: {{ $serviceGWName }}
          servicePort: {{ $serviceGWPort }}
          {{- end -}}
  {{- end -}}
  {{- if .Values.gateway.ingress.tls }}
  tls:
{{ toYaml .Values.gateway.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
{{- end -}}
