{{- if .Values.generator.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "gravitee.generator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "gravitee.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Values.generator.image.tag | default .Chart.AppVersion | quote }}
    app.kubernetes.io/component: "{{ .Values.generator.name }}"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  annotations:
    {{- range $key, $value := .Values.generator.service.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  type: "{{ .Values.generator.service.type }}"
  ports:
    - name: {{ .Values.generator.name }}
      port: {{ .Values.generator.service.externalPort }}
      targetPort: {{ .Values.generator.service.internalPortName }}
      protocol: TCP
      {{- if and (include "common.service.supportsAppProtocol" .)  .Values.generator.service.appProtocol }}
      appProtocol: {{ .Values.generator.service.appProtocol }}
      {{- end }}
  selector:
    app.kubernetes.io/name: {{ template "gravitee.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "{{ .Values.generator.name }}"
{{- end -}}
