{{- if .Values.apim.managedServiceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "apim.serviceAccount" . }}
  annotations:
    {{- with .Values.apim.serviceAccountAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.common.annotations }}
    {{- range $key, $value := .Values.common.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
  labels:
    app.kubernetes.io/name: {{ template "gravitee.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: "{{ .Values.apim.name }}"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- if .Values.common.labels }}
    {{- range $key, $value := .Values.common.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
{{- end -}}
