{{- if .Values.api.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "gravitee.api.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "gravitee.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: "{{ .Values.api.name }}"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "gravitee.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: "{{ .Values.api.name }}"
  template:
    metadata:
      annotations:
        chaos.alpha.kubernetes.io/enabled: "{{ .Values.chaos.enabled }}"
        {{- if .Values.api.reloadOnConfigChange }}
        checksum/config: {{ include (print $.Template.BasePath "/api/api-configmap.yaml") . | sha256sum }}
        {{- end }}
      labels:
        app.kubernetes.io/name: {{ template "gravitee.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: "{{ .Values.api.name }}"
    spec:
      {{- if .Values.api.nodeSelector }}
      nodeSelector:
        {{ toYaml .Values.api.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.api.extraInitContainers }}
      initContainers:
        {{- with .Values.api.extraInitContainers }}
        {{- tpl . $ | nindent 8 }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ template "gravitee.api.fullname" . }}
          image: "{{ .Values.api.image.repository }}:{{ default .Chart.AppVersion .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          {{- if .Values.api.runAsNonRoot -}}
          securityContext:  
            runAsUser: 1001
            runAsNonRoot: true
          {{- end }}
          ports:
            - name: {{ .Values.api.service.internalPortName }}
              containerPort: {{ .Values.api.service.internalPort }}
          {{- if .Values.api.env }}
          env:
            {{- with .Values.api.env }}
            {{- tpl . $ | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- if .Values.api.lifecycle }}
          lifecycle:
            {{- if .Values.api.lifecycle.postStart }}
            postStart:
              exec:
                command: {{ .Values.api.lifecycle.postStart }}
            {{- end }}
            {{- if .Values.api.lifecycle.preStop }}
            preStop:
              exec:
                command: {{ .Values.api.lifecycle.preStop }}
            {{- end }}
          {{- end }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.api.service.internalPort }}
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            tcpSocket:
              port: {{ .Values.api.service.internalPort }}
            initialDelaySeconds: 60
            periodSeconds: 30
          resources:
{{ toYaml .Values.api.resources | indent 12 }}
          volumeMounts:
            - name: config
              mountPath: /opt/graviteeio-management-api/config/gravitee.yml
              subPath: gravitee.yml
          {{- if .Values.api.logging.debug }}
            - name: config
              mountPath: /opt/graviteeio-management-api/config/logback.xml
              subPath: logback.xml
          {{- end }}
          {{- with .Values.api.extraVolumeMounts }}
          {{- tpl . $ | nindent 12 }}
          {{- end }}
      {{- if .Values.api.image.pullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.api.image.pullSecrets }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ template "gravitee.api.fullname" . }}
        {{- with .Values.api.extraVolumes }}
          {{- tpl . $ | nindent 8 }}
        {{- end }}
{{- end -}}