{{- if and (.Values.ui.enabled) (.Values.ui.pdb.enabled) -}}
apiVersion: {{ include "common.capabilities.policy.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ template "gravitee.ui.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "gravitee.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Values.ui.image.tag | default .Chart.AppVersion | quote }}
    app.kubernetes.io/component: "{{ .Values.ui.name }}"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  {{- if .Values.ui.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.ui.pdb.maxUnavailable }}
  {{ end -}}
  {{- if .Values.ui.pdb.minAvailable }}
  minAvailable: {{ .Values.ui.pdb.minAvailable }}
  {{ end -}}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "gravitee.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: "{{ .Values.ui.name }}"
{{- end -}}