apiVersion: v1
name: apim
# When the version is modified, make sure the artifacthub.io/changes list is updated
# Also update CHANGELOG.md
version: 1.29.14
appVersion: 1.30.26
description: Official Gravitee.io Helm chart for API Management
home: https://gravitee.io
sources:
  - https://github.com/gravitee-io
icon: https://avatars2.githubusercontent.com/u/12655666?s=200&v=4
keywords:
  - gravitee.io
  - gravitee
  - graviteeio 
  - API
  - API Management
  - apim
kubeVersion: ">=1.16.0-0"
