{{- if .Values.gateway.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "gravitee.gateway.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "gravitee.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Values.gateway.image.tag | default .Chart.AppVersion | quote }}
    app.kubernetes.io/component: "{{ .Values.gateway.name }}"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  annotations:
    {{- range $key, $value := .Values.gateway.service.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  type: "{{ .Values.gateway.service.type }}"
  ports:
    - port: {{ .Values.gateway.service.externalPort }}
      targetPort: {{ .Values.gateway.service.internalPort }}
      protocol: TCP
      {{- if and (include "common.service.supportsAppProtocol" .)  .Values.gateway.service.appProtocol }}
      appProtocol: {{ .Values.gateway.service.appProtocol }}
      {{- end }}
      name: {{ .Values.gateway.name }}
    {{- if .Values.gateway.services.core.service.enabled }}
    - port: {{ .Values.gateway.services.core.service.externalPort }}
      targetPort: {{ .Values.gateway.services.core.http.port }}
      protocol: TCP
      {{- if and (include "common.service.supportsAppProtocol" .)  .Values.gateway.services.core.service.appProtocol }}
      appProtocol: {{ .Values.gateway.services.core.service.appProtocol }}
      {{- end }}
      name: {{ .Values.gateway.name }}-technical
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ template "gravitee.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "{{ .Values.gateway.name }}"
{{- end -}}
