{{- if .Values.gateway.services.core.http.enabled -}}
{{- if .Values.gateway.services.core.ingress.enabled -}}
{{- $serviceAPIName := include "gravitee.gateway.fullname" . -}}
{{- $serviceAPIPort := .Values.gateway.services.core.service.externalPort -}}
{{- $ingressPath   := .Values.gateway.services.core.ingress.path -}}
{{- $apiVersion := include "common.capabilities.ingress.apiVersion" . -}}
apiVersion: {{ $apiVersion }}
kind: Ingress
metadata:
  name: {{ template "gravitee.gateway.fullname" . }}-technical
  labels:
    app.kubernetes.io/name: {{ template "gravitee.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Values.gateway.image.tag | default .Chart.AppVersion | quote }}
    app.kubernetes.io/component: "{{ .Values.gateway.name }}"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  {{- if .Values.gateway.services.core.ingress.annotations }}  
  annotations:
    {{- include "common.ingress.annotations.render" (dict "annotations" .Values.gateway.services.core.ingress.annotations "ingressClassName" .Values.gateway.services.core.ingress.ingressClassName "openshift" .Values.openshift "context" $) | nindent 4 }}
  {{- end }}
spec:
  {{- if and (eq (include "common.ingress.supportsIngressClassname" .) "true") (.Values.gateway.services.core.ingress.ingressClassName) (ne .Values.gateway.services.core.ingress.ingressClassName "none") }}
  ingressClassName: {{ .Values.gateway.services.core.ingress.ingressClassName | quote }}
  {{- end }}
  rules:
  {{- range $host := .Values.gateway.services.core.ingress.hosts }}
  - host: {{ $host }}
    http:
      paths:
      - pathType: Prefix
        path: {{ $ingressPath }}
        backend:
          {{- if (eq $apiVersion "networking.k8s.io/v1") }}
          service:
            name: {{ $serviceAPIName }}
            port:
              number: {{ $serviceAPIPort }}
          {{ else }}
          serviceName: {{ $serviceAPIName }}
          servicePort: {{ $serviceAPIPort }}
          {{- end -}}
  {{- end -}}
  {{- if .Values.gateway.services.core.ingress.tls }}
  tls:
{{ toYaml .Values.gateway.services.core.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
{{- end -}}
