{{- if .Values.gateway.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "gravitee.gateway.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "gravitee.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Values.gateway.image.tag | default .Chart.AppVersion | quote }}
    app.kubernetes.io/component: "{{ .Values.gateway.name }}"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  annotations:
    {{- range $key, $value := .Values.gateway.service.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  type: "{{ .Values.gateway.service.type }}"
  {{- if eq .Values.gateway.service.type "NodePort" "LoadBalancer" }}
  externalTrafficPolicy: {{ .Values.gateway.service.externalTrafficPolicy }}
  {{- end }}
  ports:
    - port: {{ .Values.gateway.service.externalPort }}
      targetPort: {{ .Values.gateway.service.internalPort }}
      protocol: TCP
      {{- if (include "common.service.supportsAppProtocol" .) }}
      {{ if .Values.gateway.service.appProtocol }}
      appProtocol: {{ .Values.gateway.service.appProtocol }}
      {{ else if .Values.gateway.ssl.enabled }}
      appProtocol: https
      {{ else }}
      appProtocol: http
      {{ end }}
      {{- end }}
      name: {{ .Values.gateway.name | trunc 63 | trimSuffix "-" }}
    {{- if .Values.gateway.services.core.service.enabled }}
    - port: {{ .Values.gateway.services.core.service.externalPort }}
      targetPort: {{ .Values.gateway.services.core.http.port }}
      protocol: TCP
      {{- if (include "common.service.supportsAppProtocol" .) }}
      {{ if  .Values.gateway.services.core.service.appProtocol }}
      appProtocol: {{ .Values.gateway.services.core.service.appProtocol }}
      {{ else }}
      appProtocol: http
      {{ end }}
      {{- end }}
      name: {{ printf "%s-%s" (.Values.gateway.name | trunc 53 | trimSuffix "-") "technical" }}
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ template "gravitee.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "{{ .Values.gateway.name }}"
{{- end -}}
