{{- if .Values.api.enabled -}}
{{- if .Values.api.autoscaling.enabled }}
{{- $apiVersion := include "common.capabilities.autoscaling.apiVersion" . -}}
apiVersion: {{ $apiVersion }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "gravitee.api.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "gravitee.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: "{{ .Values.api.name }}"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "gravitee.api.fullname" . }}
  minReplicas: {{ .Values.api.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.api.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      {{- if (eq $apiVersion "autoscaling/v2") }}
      target:
        type: Utilization
        averageUtilization: {{ .Values.api.autoscaling.targetAverageUtilization }}
      {{ else }}
      targetAverageUtilization: {{ .Values.api.autoscaling.targetAverageUtilization }}
      {{- end -}}
{{- if .Values.api.autoscaling.targetMemoryAverageUtilization }}
  - type: Resource
    resource:
      name: memory
      {{- if (eq $apiVersion "autoscaling/v2") }}
      target:
        type: Utilization
        averageUtilization: {{ .Values.api.autoscaling.targetMemoryAverageUtilization }}
      {{ else }}
      targetAverageUtilization: {{ .Values.api.autoscaling.targetMemoryAverageUtilization }}
      {{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}